### PR TITLE
Delete_File _Folder 

### PR DESCRIPTION
**Pull request by ssali2022**
US-08: feature file,  step defs, page classes   pushed to review

### CODE REVIEW

**Comment by ssali2022** [comment]
Guys, by the way I am using Pull request feature from IntelliJ. Can you please respond to check if you see my msgs?

**Review by loshmi04 — CHANGES_REQUESTED** [review]
Hey Salma , i found one of your elements is not good pls change that
Screenshot 2022-11-10 084017
Screenshot (105)

**Review by ssali2022 — COMMENTED** [review]
Please review as all fixed Thank you

**Comment by ssali2022** [comment]
Hey Milos! Thank you I had to relocate my element, so all updated and sent back for review. Please check. Thank you

**Comment by ssali2022** [comment]
> Hey Salma , i found one of your elements is not good pls change that Screenshot 2022-11-10 084017 Screenshot (105)

passed

**Comment by DeeAdal** [comment]
It's running perfect!

**Review by DeeAdal — APPROVED** [review]

**Review by loshmi04 — APPROVED** [review]
its very unstable app

**Comment by ssali2022** [comment]
thats true. Thank you guys for your amazing work!

**Pull request merged**
